name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - uses: astral-sh/setup-uv@v5

      - name: Initialize project
        run: make init PROJECT_NAME=ci-temp

      - name: Install dependencies
        run: make install

      - name: Lint code
        run: make lint

      - name: Run tests
        run: make test

